name: Mirror to Codeberg (no history)

on:
  push:
    branches: [main]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1  # No history

      - name: Remove Git history
        run: rm -rf .git

      - name: Reinitialize and push to Codeberg
        run: |
          git init
          git config user.name "anon"
          git config user.email "anon@example.com"
          git remote add origin https://SageWaffle:${{ secrets.CODEBERG_TOKEN }}@codeberg.org/SageWaffle/Destiny-Chat-Sidebar.git
          git add .
          git commit -m "Anonymized source sync"
          git push --force origin master
